// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using DndDungeons.API.Data;

#nullable disable

namespace DndDungeons.API.Migrations.DndDungeonsDb
{
    [DbContext(typeof(DndDungeonsDbContext))]
    [Migration("20231209135622_Second Migration")]
    partial class SecondMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NZWalks.API.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("56f83232-0bf4-447d-b7c6-2bf5a4c818a6"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("29f006ee-4961-4de1-867d-0797eb080e91"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("f28c19c1-ef2b-48f5-8741-e259080d0640"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.DndRegion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9b5aaaca-4280-4fb0-a72a-2a2e460f2c79"),
                            Code = "UND",
                            Name = "Menzoberranzan",
                            RegionImageUrl = "https://db4sgowjqfwig.cloudfront.net/campaigns/97510/assets/1064433/The_City_of_Menzoberranzan.jpg?1586500934"
                        },
                        new
                        {
                            Id = new Guid("ed8a75d6-28c2-409d-b77a-47a4fa72e94b"),
                            Code = "BG",
                            Name = "Baldur's Gate",
                            RegionImageUrl = "https://static.wikia.nocookie.net/forgottenrealms/images/c/c4/Baldur%27s_Gate_overview_BG3.png/revision/latest?cb=20190606171350"
                        },
                        new
                        {
                            Id = new Guid("a836c716-acdb-4961-b141-75f66b4703cc"),
                            Code = "CLP",
                            Name = "Calimport",
                            RegionImageUrl = "https://db4sgowjqfwig.cloudfront.net/campaigns/230022/assets/1289938/Calimport.webp?1667532906"
                        },
                        new
                        {
                            Id = new Guid("54e9293e-b843-457d-9be3-8cb95d5e86ed"),
                            Code = "ETB",
                            Name = "Eltabbar",
                            RegionImageUrl = "https://preview.redd.it/the-city-of-eltabbar-capital-city-of-thay-at-night-with-a-v0-46wdg9cm83fa1.png?auto=webp&s=28d424c1c7e6854d87f9d7e22e652d75b6217a2a"
                        },
                        new
                        {
                            Id = new Guid("83b06436-c95c-400f-a8df-03037f407b42"),
                            Code = "ATK",
                            Name = "Athkatla",
                            RegionImageUrl = "https://www.worldanvil.com/media/cache/cover/uploads/images/ac86f132ef5cffd6486891449e00a89e.webp"
                        });
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Dungeon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DungeonImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Dungeons");
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSizeInBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Dungeon", b =>
                {
                    b.HasOne("NZWalks.API.Models.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NZWalks.API.Models.Domain.DndRegion", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
